services:
    # 1. Nginx Reverse Proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  # 2. ACME Companion (Pengurus HTTPS)
  acme-companion:
    image: nginxproxy/acme-companion
    environment:
      # Email ini bebas, dipakai oleh Let's Encrypt
      - DEFAULT_EMAIL=admin@besewapestakita.duckdns.org
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    restart: always

  # 3. Backend API Kamu
  web:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - VIRTUAL_HOST=besewapestakita.duckdns.org
      - LETSENCRYPT_HOST=besewapestakita.duckdns.org
      - VIRTUAL_PORT=8000
    restart: always

volumes:
  certs:
  vhost:
  html:
  acme: